[package]
name = "waitx"
version = "0.2.4"
edition = "2024"
license = "MIT"
repository = "https://github.com/eschwart/waitx"
authors = ["Evan Schwartzentruber <ejsch03@gmail.com>"]
description = "Blazingly fast and minimal signaling primitive."
keywords = ["signal", "channel", "sync", "atomic", "lightweight"]
categories = ["concurrency"]
exclude = [".github/", ".gitignore", "LICENSE", "benches/", "docs/"]

[dependencies]
parking_lot = "0.12.5"

[dev-dependencies]
criterion = "0.7.0"
crossbeam-channel = "0.5.15"
flume = "0.11.1"

[[bench]]
name = "ping_pong"
harness = false

[profile.release]
lto = true
codegen-units = 1
